### ISSUE TITLE
Body Markings Issues

### ISSUE THREAD

**Issue by DaddyArchon** [cebutris/MithraBayport#50]
#### Description of issue

Body markings seem to not mesh with the torso segment of sprits.

#### Difference between expected and actual behavior

When selecting the "Belly and Butt" body markings, the torso portion of the marking does not display on the model.

#### Steps to reproduce 

You can reproduce this issue by creating a female Akula and adding the "Belly and Butt" body marking. 

#### Specific information for locating

As said before, it's anything that goes over the torso of the body sprite in terms of body markings. When I made a male Akula, the same issue arose.

#### Length of time in which bug has been known to occur

Any time using a torso-marking body marking sprite decal.

#### Client version, Server revision & Game ID

Client Version: 512
Server Revision: Revision Unknown
Game ID: bXF-dzY4
Current map: NDV Immortal

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.
![bodymarkingissue](https://user-images.githubusercontent.com/45769993/49754627-37f8da00-fc7c-11e8-960c-b838ae84a5e1.png)

- [o ] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [o ] Issue could be reproduced in multiple rounds
- [o ] Issue happened in a recent (less than 7 days ago) round
- [o ] [Couldn't find an existing issue about this](https://github.com/Baystation12/Baystation12/issues)

**Comment by Michiyamenotehifunana** [comment]
This seems to be related to the marking's code. I shall look over the code and see if there's any discrepancies, as the tigerstripe fullbody marking renders on the chest with no issues.

**Comment by Michiyamenotehifunana** [comment]
Fixed with #67.
