### ISSUE TITLE
Lots of missing facial hair options

### ISSUE THREAD

**Issue by BaronVonTerra** [cebutris/MithraBayport#53]
#### Description of issue
Same as what it says on the tin

#### Difference between expected and actual behavior
Only two facial hair options for all species.
Should be quite a number more.

#### Steps to reproduce 
Check facial hair.

#### Client version, Server revision & Game ID

Unknown revision
Game ID: bXP-bEKX

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [x ] Issue could be reproduced at least once
- [x ] Issue could be reproduced by different players
- [ x] Issue could be reproduced in multiple rounds
- [ ] Issue happened in a recent (less than 7 days ago) round
- [ ] [Couldn't find an existing issue about this](https://github.com/Baystation12/Baystation12/issues)

**Comment by Michiyamenotehifunana** [comment]
This is most likely related to the facial hair whitelist fuckery we did to let custom species use hairs,

**Comment by cebutris** [comment]
Yeah- I made hair global but I forgot facial hair. I'll fix this at some point (I.E when I'm not busy and I remember)

**Comment by cebutris** [comment]
Fixed in #66
