### ISSUE TITLE
Sinta'Unathi and Yeosa'Unathi have the same sprite.

### ISSUE THREAD

**Issue by BaronVonTerra** [cebutris/MithraBayport#54]
#### Description of issue
Unathi and Yeosa'Unathi use the same sprite, that sprite being the baystation one.

#### Difference between expected and actual behavior
Expected: Unathi would use the Polaris unathi body sprite and the Yeosa'Unathi would use the Bayport sprite
Actual: Both species of unathi use the Bayport sprite.

#### Steps to reproduce 
Go to species tab. Select relevant species.

#### Client version, Server revision & Game ID

Revision unknown
Game ID: bXP-bEKX

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [ ] Issue happened in a recent (less than 7 days ago) round
- [ ] [Couldn't find an existing issue about this](https://github.com/Baystation12/Baystation12/issues)

**Comment by Michiyamenotehifunana** [comment]
We still have not implemented the humanlike Unathi race. We are still figuring out how to best implement them.

**Comment by cebutris** [comment]
The core of this issue was adressed in #68
