### ISSUE TITLE
Custom Species Coloration

### ISSUE THREAD

**Issue by Xelakian** [cebutris/MithraBayport#61]
#### Description of issue
Custom Species Body Color doesn't change their body color, at least not for human based custom species.

#### Difference between expected and actual behavior
Expected the Body Color selector to change the character's body color. It did not.

#### Steps to reproduce 
Choose Custom Species, choose a color from the body color selector

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [ ] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [ ] Issue happened in a recent (less than 7 days ago) round
- [ ] [Couldn't find an existing issue about this](https://github.com/Baystation12/Baystation12/issues)

**Comment by Michiyamenotehifunana** [comment]
Bay's human sprites run off a unique skin tone system, which means that we have to make a seperate human body sprite for custom species memes.

**Comment by cebutris** [comment]
This is limited to just humans, right?

**Comment by cebutris** [comment]
Assuming this is limited to just humans- fixed in #69
